const TRIGRAMS = [
  {
    name: `Ch'ien,  lo Creativo,  el Cielo`,
    bin: 0b111,
  },
  {
    name: `Kun,  lo Receptivo,  la Tierra`,
    bin: 0b000,
  },
  {
    name: `Chen,  lo Suscitativo,  el Trueno`,
    bin: 0b100,
  },
  {
    name: `K'an,  lo Abismal,  el Agua`,
    bin: 0b010,
  },
  {
    name: `Ken,  el Aquietamiento,  la Montaña`,
    bin: 0b001,
  },
  {
    name: `Sun,  lo Suave,  el Viento,  la Madera`,
    bin: 0b011,
  },
  {
    name: `Li,  lo Adherente,  el Fuego`,
    bin: 0b101,
  },
  {
    name: `Tui,  lo Sereno,  el Lago`,
    bin: 0b110,
  },
]

const triByBin = new Map(TRIGRAMS.map((t) => [t.bin, t]))

const HEXAGRAMS = [
  {
    order: 1,
    bin: 0b111111,
    name: `Ch'ien  /  Lo Creativo`,
    up: triByBin.get(0b111).name,
    down: triByBin.get(0b111).name,
    mutable1: 'Al comienzo un nueve significa:\nDragón cubierto. No actúes.',
    mutable2:
      'Nueve en el segundo puesto significa:\nDragón que aparece sobre el campo.\nEs propicio ver al gran hombre.',
    mutable3:
      'Nueve en el tercer puesto significa:\nEl noble es creativamente activo todo el día.\nAun por la noche lo embarga la preocupación interior.\nPeligro. Ninguna tacha.',
    mutable4:
      'Nueve en el cuarto puesto significa:\nVacilante elevación sobre el precipicio. Ninguna tacha.',
    mutable5:
      'Nueve en el quinto puesto significa:\nDragón que vuela en el cielo.\nEs propicio ver al gran hombre.',
    mutable6:
      'Al tope un nueve significa:\nDragón soberbio tendrá que arrepentirse.',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia.',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable.',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%202.png',
  },
  {
    order: 2,
    bin: 0b000000,
    name: `K'un  /  Lo Receptivo`,
    up: triByBin.get(0b000).name,
    down: triByBin.get(0b000).name,
    mutable1:
      'Al comienzo un seis significa:\nCuando se pisa escarcha, se aproxima el hielo firme.',
    mutable2:
      'Seis en el segundo puesto significa:\nRectilíneo, rectangular, grande.\nSin propósito, y sin embargo nada queda que no se vea fomentado.',
    mutable3:
      'Seis en el tercer puesto significa:\nLíneas ocultas; se es capaz de permanecer perseverante.\nSi acaso sigues al servicio de un rey,\n¡no busques obras, sino llévalas a cabo!',
    mutable4:
      'Seis en el cuarto puesto significa:\nBolsa atada. Ninguna tacha; ningún elogio.',
    mutable5:
      'Seis en el quinto puesto significa:\nRopa interior amarilla trae elevada ventura.',
    mutable6:
      'Al tope un seis significa:\nDragones luchan en la pradera.\nSu sangre es negra y amarilla.',
    dictamen:
      'Lo Receptivo obra elevado éxito, propiciante por la perseverancia de una yegua. Cuando el noble ha de emprender algo y quiere avanzar, se extravía; mas si va en seguimiento encuentra conducción. Es propicio encontrar amigos al Oeste y al Sur, evitar los amigos al Este y al Norte. Una tranquila perseverancia trae ventura.',
    imagen:
      'El estado de la Tierra es la receptiva entrega. Así el noble, de naturaleza amplia, sostiene el mundo externo.',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%203.png',
  },
  {
    order: 3,
    bin: 0b100010,
    name: `Chun  /  La Dificultad Inicial`,
    up: triByBin.get(0b010).name,
    down: triByBin.get(0b100).name,
    mutable1:
      'Al comienzo un nueve significa:\nVacilación y traba.\nEs propicio permanecer perseverante.\nEs propicio designar ayudantes.',
    mutable2:
      'Seis en el segundo puesto significa:\nSe apilan dificultades. Caballo y carro se separan.\nÉl no es un raptor,\nva a cortejar en el debido plazo.\nLa doncella es casta, no se promete.\nDiez años, luego promete.',
    mutable3:
      'Seis en el tercer puesto significa:\nEl que caza al ciervo sin guardamonte,\nlo único que logra es extraviarse en el bosque.\nEl noble capta los signos del tiempo\ny prefiere desistir.\nContinuar acarrea humillación.',
    mutable4:
      'Seis en el cuarto puesto significa:\nCaballo y carro se separan.\n¡Busca la unión!\nAcudir trae ventura.\nTodo obra de un modo propicio.',
    mutable5:
      'Nueve en el quito puesto significa:\nDificultades en bendecir.\nPequeña perseverancia trae ventura.\nGran perseverancia trae desventura.',
    mutable6:
      'Al tope un seis significa:\nCaballo y carro se separan.\nLágrimas de sangre se derraman.',
    dictamen:
      'Lo Dificultad Inicial obra elevado éxito. Propicio en virtud de la perseverancia. No debe emprenderse nada. Es propicio designar ayudantes.',
    imagen:
      'Nubes y trueno: la imagen de La Dificultad Inicial. Así el noble actúa desenmarañando y ordenando.',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%204.png',
  },
  {
    order: 4,
    bin: 0b010001,
    name: `Meng  /  La Necedad Juvenil`,
    up: triByBin.get(0b001).name,
    down: triByBin.get(0b010).name,
    mutable1:
      'Al comienzo un seis significa:\nCon el fin de desarrollar al necio\nes propicio disciplinar al hombre.\nDeben quitarse las trabas.\nContinuar así trae humillación.',
    mutable2:
      'Nueve en el segundo puesto significa:\nSoportar a los necios con benevolencia trae ventura.\nSaber tomar a las mujeres trae ventura.\nEl hijo es apto para administrar la casa.',
    mutable3:
      'Seis en el tercer puesto significa:\nNo has de tomar una muchacha\nque ve a un hombre de bronce\ny ya no es dueña de sí misma.\nNada es propicio.',
    mutable4:
      'Seis en el cuarto puesto significa:\nNecedad con cortedad trae humillación.',
    mutable5:
      'Seis en el quinto puesto significa:\nNecedad infantil aporta ventura.',
    mutable6:
      'Al tope un nueve significa:\nAl castigar la necedad no es propicio\ncometer abusos.\nSólo es propicio defenderse de abusos.',
    dictamen:
      'La Necedad Juvenil tiene éxito. No soy yo quien busca al joven necio, el joven necio me busca a mí. Al primer oráculo doy razón. Si pregunta dos, tres veces, es molestia. Cuando molesta no doy información. Es propicia la perseverancia.',
    imagen:
      'En lo bajo, al pie de la montaña, surge un manantial: la imagen de la juventud. Así el noble, mediante su actuación escrupulosa, sustenta su carácter.',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%205.png',
  },
  {
    order: 5,
    bin: 0b111010,
    name: `Hsü  /  La Espera (La Alimentación)`,
    up: triByBin.get(0b010).name,
    down: triByBin.get(0b111).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%206.png',
  },
  {
    order: 6,
    bin: 0b010111,
    name: `Sung  /  El Conflicto (El Pleito)`,
    up: triByBin.get(0b111).name,
    down: triByBin.get(0b010).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%207.png',
  },
  {
    order: 7,
    bin: 0b010000,
    name: `Shih  /  El Ejército`,
    up: triByBin.get(0b000).name,
    down: triByBin.get(0b010).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%208.png',
  },
  {
    order: 8,
    bin: 0b000010,
    name: `Pi  /  La Solidaridad (El mantenerse unido)`,
    up: triByBin.get(0b010).name,
    down: triByBin.get(0b000).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%209.png',
  },
  {
    order: 9,
    bin: 0b111011,
    name: `Hsiao Ch'u  /  La Fuerza Domesticadora de lo Pequeño`,
    up: triByBin.get(0b011).name,
    down: triByBin.get(0b111).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2010.png',
  },
  {
    order: 10,
    bin: 0b110111,
    name: `Lü  /  El Porte (La Pisada)`,
    up: triByBin.get(0b111).name,
    down: triByBin.get(0b110).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2011.png',
  },
  {
    order: 11,
    bin: 0b111000,
    name: `T'ai  /  La Paz`,
    up: triByBin.get(0b000).name,
    down: triByBin.get(0b111).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2012.png',
  },
  {
    order: 12,
    bin: 0b000111,
    name: `P'i  /  El Estancamiento`,
    up: triByBin.get(0b111).name,
    down: triByBin.get(0b000).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2013.png',
  },
  {
    order: 13,
    bin: 0b101111,
    name: `T'ung Jen  /  Comunidad con los Hombres`,
    up: triByBin.get(0b111).name,
    down: triByBin.get(0b101).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2014.png',
  },
  {
    order: 14,
    bin: 0b111101,
    name: `Ta Yu  /  La Posesión de lo Grande`,
    up: triByBin.get(0b101).name,
    down: triByBin.get(0b111).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2015.png',
  },
  {
    order: 15,
    bin: 0b001000,
    name: `Ch'ien  /  La Modestia`,
    up: triByBin.get(0b000).name,
    down: triByBin.get(0b001).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2016.png',
  },
  {
    order: 16,
    bin: 0b000100,
    name: `Yü  /  El Entusiasmo`,
    up: triByBin.get(0b100).name,
    down: triByBin.get(0b000).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2017.png',
  },
  {
    order: 17,
    bin: 0b100110,
    name: `Sui  /  El Seguimiento`,
    up: triByBin.get(0b110).name,
    down: triByBin.get(0b100).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2018.png',
  },
  {
    order: 18,
    bin: 0b011001,
    name: `Ku  /  El Trabajo en lo Echado a Perder`,
    up: triByBin.get(0b001).name,
    down: triByBin.get(0b011).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2019.png',
  },
  {
    order: 19,
    bin: 0b110000,
    name: `Lin  /  El Acercamiento`,
    up: triByBin.get(0b000).name,
    down: triByBin.get(0b110).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2020.png',
  },
  {
    order: 20,
    bin: 0b000011,
    name: `Kuan  /  La Contemplación (La Vista)`,
    up: triByBin.get(0b011).name,
    down: triByBin.get(0b000).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2021.png',
  },
  {
    order: 21,
    bin: 0b100101,
    name: `Shih Ho  /  La Mordedura Tajante`,
    up: triByBin.get(0b101).name,
    down: triByBin.get(0b100).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2022.png',
  },
  {
    order: 22,
    bin: 0b101001,
    name: `Pi  /  La Gracia (Lo Agraciado)`,
    up: triByBin.get(0b001).name,
    down: triByBin.get(0b101).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2023.png',
  },
  {
    order: 23,
    bin: 0b000001,
    name: `Po  /  La Desintegración`,
    up: triByBin.get(0b001).name,
    down: triByBin.get(0b000).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2024.png',
  },
  {
    order: 24,
    bin: 0b100000,
    name: `Fu  /  El Retorno (El Tiempo del Solsticio)`,
    up: triByBin.get(0b000).name,
    down: triByBin.get(0b100).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2025.png',
  },
  {
    order: 25,
    bin: 0b100111,
    name: `Wu Wang  /  La Inocencia (Lo Inesperado)`,
    up: triByBin.get(0b111).name,
    down: triByBin.get(0b100).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2026.png',
  },
  {
    order: 26,
    bin: 0b111001,
    name: `Ta Ch'u  /  La Fuerza Domesticadora de lo Grande`,
    up: triByBin.get(0b001).name,
    down: triByBin.get(0b111).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2027.png',
  },
  {
    order: 27,
    bin: 0b100001,
    name: `I  /  Las Comisuras de la Boca (La Nutrición)`,
    up: triByBin.get(0b001).name,
    down: triByBin.get(0b100).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2028.png',
  },
  {
    order: 28,
    bin: 0b011110,
    name: `Ta Kuo  /  La Preponderancia de lo Grande`,
    up: triByBin.get(0b110).name,
    down: triByBin.get(0b011).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2029.png',
  },
  {
    order: 29,
    bin: 0b010010,
    name: `K'an  /  Lo Abismal, El Agua`,
    up: triByBin.get(0b010).name,
    down: triByBin.get(0b010).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2030.png',
  },
  {
    order: 30,
    bin: 0b101101,
    name: `Li  /  Lo Adherente, El Fuego`,
    up: triByBin.get(0b101).name,
    down: triByBin.get(0b101).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2031.png',
  },
  {
    order: 31,
    bin: 0b001110,
    name: `Hsien  /  El Influjo (El Cortejo)`,
    up: triByBin.get(0b110).name,
    down: triByBin.get(0b001).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2032.png',
  },
  {
    order: 32,
    bin: 0b011100,
    name: `Heng  /  La Duración`,
    up: triByBin.get(0b100).name,
    down: triByBin.get(0b011).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2033.png',
  },
  {
    order: 33,
    bin: 0b001111,
    name: `Tun  /  La Retirada`,
    up: triByBin.get(0b111).name,
    down: triByBin.get(0b001).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2034.png',
  },
  {
    order: 34,
    bin: 0b111100,
    name: `Ta Chuang  /  El Poder de lo Grande`,
    up: triByBin.get(0b100).name,
    down: triByBin.get(0b111).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2035.png',
  },
  {
    order: 35,
    bin: 0b000101,
    name: `Chin  /  El Progreso`,
    up: triByBin.get(0b101).name,
    down: triByBin.get(0b000).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2036.png',
  },
  {
    order: 36,
    bin: 0b101000,
    name: `Ming I  /  El Oscurecimiento de la Luz`,
    up: triByBin.get(0b000).name,
    down: triByBin.get(0b101).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2037.png',
  },
  {
    order: 37,
    bin: 0b101011,
    name: `Chia Jen  /  El Clan (La Familia)`,
    up: triByBin.get(0b011).name,
    down: triByBin.get(0b101).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2038.png',
  },
  {
    order: 38,
    bin: 0b110101,
    name: `K'uei  /  El Antagonismo (La Oposición)`,
    up: triByBin.get(0b101).name,
    down: triByBin.get(0b110).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2039.png',
  },
  {
    order: 39,
    bin: 0b001010,
    name: `Chien  /  El Impedimento`,
    up: triByBin.get(0b010).name,
    down: triByBin.get(0b001).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2040.png',
  },
  {
    order: 40,
    bin: 0b010100,
    name: `Hsieh  /  La Liberación`,
    up: triByBin.get(0b100).name,
    down: triByBin.get(0b010).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2041.png',
  },
  {
    order: 41,
    bin: 0b110001,
    name: `Sun  /  La Merma`,
    up: triByBin.get(0b001).name,
    down: triByBin.get(0b110).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2042.png',
  },
  {
    order: 42,
    bin: 0b100011,
    name: `I  /  El Aumento`,
    up: triByBin.get(0b011).name,
    down: triByBin.get(0b100).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2043.png',
  },
  {
    order: 43,
    bin: 0b111110,
    name: `Kuai  /  El Desbordamiento`,
    up: triByBin.get(0b110).name,
    down: triByBin.get(0b111).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2044.png',
  },
  {
    order: 44,
    bin: 0b011111,
    name: `Kou  /  El Ir al Encuentro (La Complacencia)`,
    up: triByBin.get(0b111).name,
    down: triByBin.get(0b011).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2045.png',
  },
  {
    order: 45,
    bin: 0b000110,
    name: `Ts'ui  /  La Reunión (La Recolección)`,
    up: triByBin.get(0b110).name,
    down: triByBin.get(0b000).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2046.png',
  },
  {
    order: 46,
    bin: 0b011000,
    name: `Sheng  /  La Subida (El Empuje hacia Arriba)`,
    up: triByBin.get(0b000).name,
    down: triByBin.get(0b011).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2047.png',
  },
  {
    order: 47,
    bin: 0b010110,
    name: `K'un  /  La Desazón (La Opresión, El Agotamiento)`,
    up: triByBin.get(0b110).name,
    down: triByBin.get(0b010).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2048.png',
  },
  {
    order: 48,
    bin: 0b011010,
    name: `Ching  /  El Pozo de Agua`,
    up: triByBin.get(0b010).name,
    down: triByBin.get(0b011).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2049.png',
  },
  {
    order: 49,
    bin: 0b101110,
    name: `Ko  /  La Revolución (La Muda)`,
    up: triByBin.get(0b110).name,
    down: triByBin.get(0b101).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2050.png',
  },
  {
    order: 50,
    bin: 0b011101,
    name: `Ting  /  El Caldero`,
    up: triByBin.get(0b101).name,
    down: triByBin.get(0b011).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2051.png',
  },
  {
    order: 51,
    bin: 0b100100,
    name: `Chen  /  Lo Suscitativo (La Conmoción, El Trueno)`,
    up: triByBin.get(0b100).name,
    down: triByBin.get(0b100).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2052.png',
  },
  {
    order: 52,
    bin: 0b001001,
    name: `Ken  /  El Aquietamiento (La Montaña)`,
    up: triByBin.get(0b001).name,
    down: triByBin.get(0b001).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2053.png',
  },
  {
    order: 53,
    bin: 0b001011,
    name: `Chien  /  La Evolución (Progreso Paulatino)`,
    up: triByBin.get(0b011).name,
    down: triByBin.get(0b001).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2054.png',
  },
  {
    order: 54,
    bin: 0b110100,
    name: `Kuei Mei  /  La Muchacha que se Casa (La Desposanda)`,
    up: triByBin.get(0b100).name,
    down: triByBin.get(0b110).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2055.png',
  },
  {
    order: 55,
    bin: 0b101100,
    name: `Feng  /  La Plenitud`,
    up: triByBin.get(0b100).name,
    down: triByBin.get(0b101).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2056.png',
  },
  {
    order: 56,
    bin: 0b001101,
    name: `Lü  /  El Andariego`,
    up: triByBin.get(0b101).name,
    down: triByBin.get(0b001).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2057.png',
  },
  {
    order: 57,
    bin: 0b011011,
    name: `Sun  /  Lo Suave (Lo Penetrante, El Viento)`,
    up: triByBin.get(0b011).name,
    down: triByBin.get(0b011).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2058.png',
  },
  {
    order: 58,
    bin: 0b110110,
    name: `Tui  /  Lo Sereno, El Lago`,
    up: triByBin.get(0b110).name,
    down: triByBin.get(0b110).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2059.png',
  },
  {
    order: 59,
    bin: 0b010011,
    name: `Huan  /  La Disolución (La Dispersión)`,
    up: triByBin.get(0b011).name,
    down: triByBin.get(0b010).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2060.png',
  },
  {
    order: 60,
    bin: 0b110010,
    name: `Chieh  /  La Restricción`,
    up: triByBin.get(0b010).name,
    down: triByBin.get(0b110).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2061.png',
  },
  {
    order: 61,
    bin: 0b110011,
    name: `Chung Fu  /  La Verdad Interior`,
    up: triByBin.get(0b011).name,
    down: triByBin.get(0b110).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2062.png',
  },
  {
    order: 62,
    bin: 0b001100,
    name: `Hsiao Kuo  /  La Preponderancia de lo Pequeño`,
    up: triByBin.get(0b100).name,
    down: triByBin.get(0b001).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2063.png',
  },
  {
    order: 63,
    bin: 0b101010,
    name: `Chi Chi  /  Después de la Consumación`,
    up: triByBin.get(0b010).name,
    down: triByBin.get(0b101).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2064.png',
  },
  {
    order: 64,
    bin: 0b010101,
    name: `Wei Chi  /  Antes de la Consumación`,
    up: triByBin.get(0b101).name,
    down: triByBin.get(0b010).name,
    mutable1: 'Línea mutable 1',
    mutable2: 'Línea mutable 2',
    mutable3: 'Línea mutable 3',
    mutable4: 'Línea mutable 4',
    mutable5: 'Línea mutable 5',
    mutable6: 'Línea mutable 6',
    dictamen:
      'Lo Creativo obra elevado logro, propiciando por la perseverancia',
    imagen:
      'Pleno de fuerza es el movimiento del Cielo.\nAsí el noble se hace fuerte e infatigable',
    src: 'https://github.com/illysito/illy/blob/2cc878c55e3120fdb4e78a65143161f3a04985e1/public/imgs_cdn/characters/iChing_-%20copia%2065.png',
  },
]

export default HEXAGRAMS
